AWSTemplateFormatVersion: "2010-09-09"

Resources:
  myRDSDb:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: mytestrds
      DBName: wordpress
      Engine: MySQL
      MasterUsername: wordpress
      MasterUserPassword: w0rdpr355

Outputs:
  myRDSDBServerName:
    Description: "Name of the RDS server"
    Value: !Ref myRDSDb
