AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for basic RDS instance creation with environmental size input"
Parameters:
  EnvSize:
    Description: "Specify the Environment size"
    Default: "Small"
    Type: String
    AllowedValues:
      - Small
      - Medium
      - Large

Mappings:
  InstanceTypeMap:
    Small:
      DB: "db.t2.micro"
    Medium:
      DB: "db.t2.small"
    Large:
      DB: "db.t2.medium"

Resources:
  myRDSDb:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass:
        Fn::FindInMap: [InstanceTypeMap, Ref: EnvSize, "DB"]
      DBInstanceIdentifier: mytestrds
      DBName: wordpress
      Engine: MySQL
      MasterUsername: wordpress
      MasterUserPassword: w0rdpr355

Outputs:
  myRDSDBServerName:
    Description: "Name of the RDS server"
    Value: !Ref myRDSDb
