AWSTemplateFormatVersion: "2010-09-09"
Description: "Basic WordPress installation on EC2 instance and RDS as DB in a default VPC"

Parameters:
  EnvSize:
    Type: String
    Default: Small
    AllowedValues:
      - Small
      - Medium
      - Large
    Description: "Enter the environment Size for the wordpress"

  KeyPairName:
    Type: String
    Default: ""

  RDSInstanceName:
    Type: String
    Default: ""

  DatabaseName:
    Type: String
    Default: wordpress

  DatabaseUser:
    Type: String
    Default: wordpress

  DatabasePassword:
    Type: String
    Default: w0rdpr355
    NoEcho: true

Mappings:
  RegionMap:
    us-east-1:
      AmazonLinux: ami-0080e4c5bc078760e
    us-east-2:
      AmazonLinux: ami-0cd3dfa4e37921605
    us-west-1:
      AmazonLinux: ami-0ec6517f6edbf8044
    us-west-2:
      AmazonLinux: ami-01e24be29428c15b2
    sa-east-1:
      AmazonLinux: ami-05145e0b28ad8e0b2
    ca-central-1:
      AmazonLinux: ami-07423fb63ea0a0930
    eu-west-1:
      AmazonLinux: ami-08935252a36e25f85
    eu-west-2:
      AmazonLinux: ami-01419b804382064e4
    eu-west-3:
      AmazonLinux: ami-0dd7e7ed60da8fb83
    eu-central-1:
      AmazonLinux: ami-0cfbf4f6db41068ac
    ap-southeast-1:
      AmazonLinux: ami-05b3bcf7f311194b3
    ap-southeast-2:
      AmazonLinux: ami-02fd0b06f06d93dfc
    ap-northeast-1:
      AmazonLinux: ami-00a5245b4816c38e6
    ap-northeast-2:
      AmazonLinux: ami-00dc207f8ba6dc919
    ap-south-1:
      AmazonLinux: ami-0ad42f4f66f6c1cc9
    cn-north-1:
      AmazonLinux: ami-8e6aa0e3

  InstanceMap:
    Small:
      EC2: t2.micro
      DB: db.t2.micro
    Medium:
      EC2: t2.small
      DB: db.t2.small
    Large:
      EC2: t2.medium
      DB: db.t2.large

Resources:
  myEC2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairName
      ImageId:
        Fn::FindInMap: [RegionMap, !Ref "AWS::Region", AmazonLinux]
      InstanceType:
        Fn::FindInMap: [InstanceMap, !Ref EnvSize, EC2]
      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash
            yum install -y httpd24 httpd24-tools mod24_ssl php73 php73-devel php73-mysql php73-pdo php73-mbstring php73-gd php73-xml php73-xmlrpc php73-mcrypt php73-mysqlnd
            yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://wordpress.org/latest.tar.gz
            tar -zxvf latest.tar.gz --strip 1
            rm latest.tar.gz
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            sed -i 's/localhost/${myDB.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            sed -i 's/password_here/${DatabasePassword}/g' wp-config.php

  myDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass:
        Fn::FindInMap: [InstanceMap, Ref: EnvSize, "DB"]
      DBInstanceIdentifier: !Ref RDSInstanceName
      DBName: !Ref DatabaseName
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword

  myS3:
    Type: AWS::S3::Bucket
