AWSTemplateFormatVersion: "2010-09-09"

Description: Basic setup to initialize AWS infrastructure with VPC with public and private subnet, internet gateway.

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.10.0.0/16"
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: "default"
      Tags:
        - Key: "Name"
          Value: "myVPC"

  myPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a" # FIXME Change the AZ value with GetAZs
      CidrBlock: "10.10.10.0/24"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: "Name"
          Value: "myPublicSubnet"
      VpcId:
        Ref: myVPC

  myPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a" # FIXME Change the AZ value with GetAZs
      CidrBlock: "10.10.20.0/24"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: "Name"
          Value: "myPrivateSubnet"
      VpcId:
        Ref: myVPC

  myPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: myVPC
      Tags:
        - Key: "Name"
          Value: "myPrivateRouteTable"

  myPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: myVPC
      Tags:
        - Key: "Name"
          Value: "myPublicRouteTable"

  myPublicSubRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: myPublicRouteTable
      SubnetId:
        Ref: myPublicSubnet

  myPrivateSubRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: myPrivateRouteTable
      SubnetId:
        Ref: myPrivateSubnet

  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: "Name"
          Value: "myInternetGateway"

  myIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: myInternetGateway
      VpcId:
        Ref: myVPC

  myRouteToInternet:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref myInternetGateway
      RouteTableId: !Ref myPublicRouteTable

Outputs:
  myVPCID:
    Description: "VPC ID created by the stack"
    Value: !Ref myVPC

  myPubSub:
    Description: "Subnet ID of public subnet"
    Value: !Ref myPublicSubnet

  myPriSub:
    Description: "Subnet ID of private subnet"
    Value: !Ref myPrivateSubnet
